export const DEMO_DATA = {
  gti: 71.4,
  gti_delta: 2.1,
  last_updated: '2026-03-19 08:30:00 UTC',

  signals: [
    {
      id: 's1', asset: 'XAU/USD', category: 'Gold · Commodities', action: 'BUY',
      price: 2314.58, change: +1.2, changeP: '+1.2%',
      confidence: 0.88, bullStrength: 74, bearStrength: 26,
      volatility: 'MEDIUM', timeframes: ['Short-Term', 'Weekly', 'Global'],
      rationale: 'Safe-haven flows increasing due to elevated geopolitical stress.',
      trigger: 'Iran-Israel Escalation — Missile Exchanges',
      triggerSub: 'Verified via satellite. Trending 02:14 · 5M.',
      entry: 2341.00, stopLoss: 2290.00, target: 2427.00,
      rr: '2.00x', winRate: '1.84%', riskMod: '3.2%',
      riskAmount: 41.000, rewardAmount: 45.098,
      riskFlags: ['Sudden de-escalation', 'Strong INR data'],
    },
    {
      id: 's2', asset: 'WTI', category: 'WTI Crude Oil', action: 'BUY',
      price: 82.16, change: +0.95, changeP: '+0.95%',
      confidence: 0.82, bullStrength: 68, bearStrength: 32,
      volatility: 'HIGH', timeframes: ['Short-Term', 'Weekly'],
      rationale: 'Supply disruption risk from Strait of Hormuz naval drills.',
      trigger: 'Iran-Israel Escalation — Strait of Hormuz',
      triggerSub: 'Drone intercepts confirmed. Trending 01:30.',
      entry: 82.16, stopLoss: 79.50, target: 87.00,
      rr: '1.82x', winRate: '2.1%', riskMod: '3.2%',
      riskAmount: 26.6, rewardAmount: 48.4,
      riskFlags: ['OPEC+ supply increase', 'US SPR release'],
    },
    {
      id: 's3', asset: 'LMT', category: 'Lockheed Martin', action: 'BUY',
      price: 469.20, change: +1.4, changeP: '+1.4%',
      confidence: 0.85, bullStrength: 78, bearStrength: 22,
      volatility: 'MEDIUM', timeframes: ['Weekly', 'Global'],
      rationale: 'Defense readiness briefing signals higher procurement spend.',
      trigger: 'Iran-Israel Escalation — NATO Defense Policy',
      triggerSub: 'Defense spending realignment. Trending.',
      entry: 469.20, stopLoss: 455.00, target: 495.00,
      rr: '1.82x', winRate: '1.9%', riskMod: '3.0%',
      riskAmount: 14.2, rewardAmount: 25.8,
      riskFlags: ['Ceasefire agreement', 'Budget cuts'],
    },
    {
      id: 's4', asset: 'SPX', category: 'S&P 500', action: 'SELL',
      price: 5299.57, change: -0.18, changeP: '-0.18%',
      confidence: 0.68, bullStrength: 32, bearStrength: 68,
      volatility: 'MEDIUM', timeframes: ['Short-Term', 'Weekly'],
      rationale: 'Elevated GTI reducing broad equity risk appetite.',
      trigger: 'Iran-SP Sentiment — Risk-Off Conditions',
      triggerSub: 'Global risk appetite deteriorates.',
      entry: 5299.57, stopLoss: 5380.00, target: 5148.00,
      rr: '1.87x', winRate: '1.5%', riskMod: '1.5%',
      riskAmount: 80.43, rewardAmount: 151.57,
      riskFlags: ['Soft CPI surprise', 'Policy reassurance'],
    },
    {
      id: 's5', asset: 'EURUSD', category: 'EUR/USD Forex', action: 'SELL',
      price: 1.0821, change: -0.14, changeP: '-0.14%',
      confidence: 0.72, bullStrength: 28, bearStrength: 72,
      volatility: 'MEDIUM', timeframes: ['Short-Term'],
      rationale: 'ECB emergency statement raises EUR volatility premium.',
      trigger: 'ECB Emergency Statement — Monetary Policy',
      triggerSub: 'Rate path uncertainty elevated.',
      entry: 1.0821, stopLoss: 1.0890, target: 1.0720,
      rr: '1.46x', winRate: '1.2%', riskMod: '0.6%',
      riskAmount: 69.0, rewardAmount: 101.0,
      riskFlags: ['ECB pivot dovish', 'Dollar weakness'],
    },
    {
      id: 's6', asset: 'BTCUSD', category: 'Bitcoin', action: 'BUY',
      price: 67240, change: +0.58, changeP: '+0.58%',
      confidence: 0.58, bullStrength: 55, bearStrength: 45,
      volatility: 'HIGH', timeframes: ['Short-Term', 'Weekly'],
      rationale: 'Bitcoin flight-to-alternative-assets narrative strengthens.',
      trigger: 'Geopolitical stress — Capital flight to alternatives',
      triggerSub: 'On-chain flows show institutional accumulation.',
      entry: 67240, stopLoss: 64000, target: 72500,
      rr: '1.62x', winRate: '1.7%', riskMod: '4.8%',
      riskAmount: 3240, rewardAmount: 5260,
      riskFlags: ['Regulatory crackdown', 'Risk-off deleveraging'],
    },
  ],

  chartData: {
    OIL: {
      name: 'OIL', fullName: 'Crude Oil WTI', price: 82.16, change: +0.95, changeP: '+0.95%',
      candles: generateCandles(82.16, 60, 0.015),
    },
    GAS: {
      name: 'GAS', fullName: 'Natural Gas', price: 3.218, change: +0.008, changeP: '+0.25%',
      candles: generateCandles(3.218, 60, 0.02),
    },
    'S&P500': {
      name: 'S&P500', fullName: 'S&P 500', price: 5299.57, change: -9.43, changeP: '-0.18%',
      candles: generateCandles(5299.57, 60, 0.008),
    },
  },

  countries: [
    { code: 'IRN', name: 'Iran',          region: 'Middle East',  risk: 84, level: 'critical' },
    { code: 'ISR', name: 'Israel',         region: 'Middle East',  risk: 82, level: 'critical' },
    { code: 'RUS', name: 'Russia',         region: 'E. Europe',    risk: 78, level: 'critical' },
    { code: 'PRK', name: 'North Korea',    region: 'E. Asia',      risk: 75, level: 'high' },
    { code: 'DEU', name: 'Germany',        region: 'Europe',       risk: 74, level: 'high' },
    { code: 'TWN', name: 'Taiwan',         region: 'E. Asia',      risk: 73, level: 'high' },
    { code: 'CHN', name: 'China',          region: 'E. Asia',      risk: 70, level: 'high' },
    { code: 'UKR', name: 'Ukraine',        region: 'E. Europe',    risk: 79, level: 'critical' },
    { code: 'USA', name: 'United States',  region: 'N. America',   risk: 45, level: 'medium' },
    { code: 'IND', name: 'India',          region: 'S. Asia',      risk: 57, level: 'medium' },
    { code: 'GBR', name: 'UK',             region: 'Europe',       risk: 35, level: 'medium' },
    { code: 'FRA', name: 'France',         region: 'Europe',       risk: 42, level: 'medium' },
    { code: 'BRA', name: 'Brazil',         region: 'S. America',   risk: 28, level: 'low' },
    { code: 'AUS', name: 'Australia',      region: 'Oceania',      risk: 18, level: 'low' },
    { code: 'CAN', name: 'Canada',         region: 'N. America',   risk: 22, level: 'low' },
    { code: 'JPN', name: 'Japan',          region: 'E. Asia',      risk: 38, level: 'medium' },
    { code: 'SAU', name: 'Saudi Arabia',   region: 'Middle East',  risk: 62, level: 'high' },
    { code: 'PAK', name: 'Pakistan',       region: 'S. Asia',      risk: 60, level: 'high' },
    { code: 'SYR', name: 'Syria',          region: 'Middle East',  risk: 71, level: 'high' },
    { code: 'LBN', name: 'Lebanon',        region: 'Middle East',  risk: 65, level: 'high' },
    { code: 'NGA', name: 'Nigeria',        region: 'Africa',       risk: 44, level: 'medium' },
    { code: 'MEX', name: 'Mexico',         region: 'N. America',   risk: 32, level: 'low' },
    { code: 'ZAF', name: 'South Africa',   region: 'Africa',       risk: 30, level: 'low' },
    { code: 'IDN', name: 'Indonesia',      region: 'SE. Asia',     risk: 25, level: 'low' },
    { code: 'TUR', name: 'Turkey',         region: 'Middle East',  risk: 55, level: 'medium' },
    { code: 'VEN', name: 'Venezuela',      region: 'S. America',   risk: 48, level: 'medium' },
    { code: 'ETH', name: 'Ethiopia',       region: 'Africa',       risk: 42, level: 'medium' },
  ],

  events: [
    { id: 'e1', country: 'Iran',    region: 'Middle East',  headline: 'Strait of Hormuz Naval D...', severity: 'critical', time: '08:30', source: 'Reuters' },
    { id: 'e2', country: 'Germany', region: 'Europe',       headline: 'ECB Emergency Statement',     severity: 'high',     time: '07:50', source: 'Bloomberg' },
    { id: 'e3', country: 'Taiwan',  region: 'East Asia',    headline: 'Maritime Airspace Incursions', severity: 'high',    time: '07:15', source: 'Reuters' },
    { id: 'e4', country: 'Russia',  region: 'E. Europe',    headline: 'Energy Transit Friction',      severity: 'high',    time: '06:40', source: 'Bloomberg' },
    { id: 'e5', country: 'USA',     region: 'N. America',   headline: 'Defense Readiness Briefing',   severity: 'medium',  time: '06:05', source: 'Reuters' },
  ],

  sparkValues: [42, 55, 48, 62, 58, 65, 70, 68, 71, 69, 72, 71],

  sectorExposure: [
    { name: 'Energy',    pct: 78, color: '#ff4444' },
    { name: 'Defense',   pct: 65, color: '#00d4ff' },
  ],

  // Portfolio positions
  portfolio: {
    totalValue: 145280.50,
    totalPnL: 3241.20,
    totalPnLPct: 2.23,
    positions: [
      {
        id: 'p1',
        asset: 'XAU/USD',
        size: 5.0,
        entryPrice: 2304.50,
        currentPrice: 2314.58,
        pnl: 50.40,
        pnlPct: 0.44,
        riskRatio: 2.0,
        timeOpen: '14h 32m',
        signal: 'BUY',
        status: 'active',
      },
      {
        id: 'p2',
        asset: 'SPX',
        size: 2.5,
        entryPrice: 5320.00,
        currentPrice: 5299.57,
        pnl: -51.08,
        pnlPct: -0.38,
        riskRatio: 1.87,
        timeOpen: '22h 14m',
        signal: 'SELL',
        status: 'active',
      },
      {
        id: 'p3',
        asset: 'EURUSD',
        size: 50000,
        entryPrice: 1.0890,
        currentPrice: 1.0821,
        pnl: 3450.00,
        pnlPct: 0.63,
        riskRatio: 1.46,
        timeOpen: '3h 45m',
        signal: 'SELL',
        status: 'active',
      },
      {
        id: 'p4',
        asset: 'BTCUSD',
        size: 0.5,
        entryPrice: 67500.00,
        currentPrice: 67240.00,
        pnl: -130.00,
        pnlPct: -0.38,
        riskRatio: 1.62,
        timeOpen: '5h 20m',
        signal: 'BUY',
        status: 'active',
      },
    ],
    metrics: {
      winRate: 68.5,
      sharpeRatio: 1.84,
      maxDrawdown: -8.2,
      avgWin: 287.50,
      avgLoss: -142.30,
    },
  },

  // Live feeds/events
  feeds: [
    {
      id: 'f1',
      time: '08:30',
      timestamp: new Date(Date.now() - 2 * 60000),
      headline: 'Strait of Hormuz Naval Drills Escalate Tensions',
      region: 'Middle East',
      severity: 'critical',
      source: 'Reuters',
      impact: '+2.1% oil bid',
      countries: ['IRN', 'SAU'],
      sentiment: -0.85,
    },
    {
      id: 'f2',
      time: '07:50',
      timestamp: new Date(Date.now() - 40 * 60000),
      headline: 'ECB Emergency Statement Raises Rate Path Uncertainty',
      region: 'Europe',
      severity: 'high',
      source: 'Bloomberg',
      impact: '+1.2% EUR volatility',
      countries: ['DEU', 'FRA'],
      sentiment: -0.62,
    },
    {
      id: 'f3',
      time: '07:15',
      timestamp: new Date(Date.now() - 75 * 60000),
      headline: 'Unexpected INR Macro Strength Complicates Safe-Haven Rotation',
      region: 'South Asia',
      severity: 'medium',
      source: 'Reuters',
      impact: 'INR attractiveness improves',
      countries: ['IND'],
      sentiment: 0.15,
    },
    {
      id: 'f4',
      time: '06:40',
      timestamp: new Date(Date.now() - 110 * 60000),
      headline: 'Technology Export Restrictions Escalate Across Strategic Supply Chains',
      region: 'East Asia',
      severity: 'high',
      source: 'Bloomberg',
      impact: '+0.8% semiconductor volatility',
      countries: ['CHN', 'TWN', 'USA'],
      sentiment: -0.71,
    },
    {
      id: 'f5',
      time: '06:05',
      timestamp: new Date(Date.now() - 145 * 60000),
      headline: 'Defense Readiness Briefing Signals Higher Global Risk Posture',
      region: 'North America',
      severity: 'medium',
      source: 'Reuters',
      impact: 'Defense stocks +1.4%',
      countries: ['USA'],
      sentiment: -0.45,
    },
    {
      id: 'f6',
      time: '05:35',
      timestamp: new Date(Date.now() - 175 * 60000),
      headline: 'Energy Transit Friction Revives Continental Supply Stress',
      region: 'Eastern Europe',
      severity: 'high',
      source: 'Bloomberg',
      impact: 'Gold bid strengthens',
      countries: ['RUS', 'UKR'],
      sentiment: -0.68,
    },
  ],
}

function generateCandles(basePrice, count, volatility) {
  const candles = []
  let price = basePrice * 0.92
  for (let i = 0; i < count; i++) {
    const open  = price
    const move  = (Math.random() - 0.48) * price * volatility
    const close = Math.max(open + move, open * 0.97)
    const high  = Math.max(open, close) * (1 + Math.random() * volatility * 0.5)
    const low   = Math.min(open, close) * (1 - Math.random() * volatility * 0.5)
    candles.push({ open, close, high, low, time: i })
    price = close
  }
  return candles
}
